CREATE TABLE departments (
  ID   NUMBER(10)   NOT NULL,
  NAME VARCHAR2(50) NOT NULL
);

ALTER TABLE departments
  ADD (
  CONSTRAINT dept_pk PRIMARY KEY (ID));

CREATE TABLE employees (
  ID        NUMBER(10)    NOT NULL PRIMARY KEY,
  DEPID     NUMBER(10),
  FIRSTNAME VARCHAR2(50)  NOT NULL,
  LASTNAME  VARCHAR2(50)  NOT NULL,
  SALARY    NUMBER(20, 2) NOT NULL,
  AGE       NUMBER(3)     NOT NULL CONSTRAINT cc_limit_age CHECK (AGE > 0),
  SEX       VARCHAR2(6)   NOT NULL,
  SUPERID   NUMBER(10)
);

ALTER TABLE employees
  ADD (
  CONSTRAINT dept_fk FOREIGN KEY (DEPID) REFERENCES departments (ID));
