INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (1, 1 , 'Vova', 'Pupkin', 10000, 45, 'MALE', NULL);
INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (2, 2 , 'Petya', 'Sidorov', 15000, 52, 'MALE', NULL);
INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (3, 3 , 'Alex', 'Lozkin', 8000, 41, 'MALE', NULL);

INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (4, 1 , 'Vasya', 'Popkin', 5000, 35, 'MALE', 1);
INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (5, 1 , 'Masha', 'Sidorova', 5000, 38, 'FEMALE', 1);
INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (6, 1 , 'Katya', 'Lozkina', 4000, 43, 'FEMALE', 4);
INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (7, 1 , 'Kolya', 'Pushkin', 4000, 45, 'MALE', 4);
INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (8, 1 , 'Dima', 'Chehov', 4000, 52, 'MALE', 5);
INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (9, 1 , 'Leha', 'Kurochkin', 4000, 41, 'MALE', 5);

INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (10, 2 , 'Marina', 'Kuznecova', 4500, 36, 'FEMALE', 2);
INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (11, 2 , 'Dima', 'Kozlov', 4100, 33, 'MALE', 10);
INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (12, 2 , 'Serg', 'Sheva', 3800, 41, 'MALE', 10);
INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (13, 2 , 'Ruslan', 'Bragin', 3950, 59, 'MALE', 10);
INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (14, 2 , 'Dolf', 'Lungrand', 3900, 28, 'MALE', 10);
INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (15, 2 , 'Gena', 'Martishkin', 3700, 29, 'MALE', 10);

INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (16, 3 , 'Zhan', 'Klod', 4200, 47, 'MALE', 3);
INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (17, 3 , 'Gulia', 'Timoshenko', 4300, 55, 'FEMALE', 3);
INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (18, 3 , 'Pol', 'Belmondo', 4350, 42, 'MALE', 3);
INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (19, 3 , 'Luchano', 'Povorrotti', 2500, 23, 'MALE', 17);
INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (20, 3 , 'Marina', 'Galushko', 2600, 25, 'FEMALE', 17);
INSERT INTO EMPLOYEES (ID, DEPID, FIRSTNAME, LASTNAME, SALARY, AGE, SEX, SUPERID)
VALUES (21, 3 , 'Fredi', 'Kruger', 2950, 29, 'MALE', 18);