INSERT INTO DEPARTMENTS (ID, NAME) VALUES (1, 'IT');
INSERT INTO DEPARTMENTS (ID, NAME) VALUES (2, 'MANAGE');
INSERT INTO DEPARTMENTS (ID, NAME) VALUES (3, 'SALE');
INSERT INTO DEPARTMENTS (ID, NAME) VALUES (4, 'TEST');
INSERT INTO DEPARTMENTS (ID, NAME) VALUES (5, 'DELIVERY');
INSERT INTO DEPARTMENTS (ID, NAME) VALUES (6, 'CLEAN');
