SELECT DISTINCT D.NAME AS department_name, 
    COUNT (E.ID) OVER (PARTITION BY D.ID) AS Amount_of_staff,
    COUNT (CASE WHEN E.SEX='MALE' THEN 1 END) OVER (PARTITION BY D.ID) AS amount_of_male,
    COUNT (CASE WHEN E.SEX='FEMALE' THEN 1 END) OVER (PARTITION BY D.ID) AS amount_of_female,
    TRUNC (AVG (E.SALARY) OVER (PARTITION BY D.ID), 2) AS AVG_salary,
    TRUNC (AVG (DECODE (E.SEX, 'MALE', E.SALARY)) OVER (PARTITION BY D.ID), 2) AS avg_male_salary,
    TRUNC (AVG (DECODE (E.SEX, 'FEMALE', E.SALARY)) OVER (PARTITION BY D.ID), 2) AS avg_female_salary,
    LISTAGG (E.LASTNAME, ', ') WITHIN GROUP (ORDER BY E.LASTNAME) OVER (PARTITION BY D.ID) AS last_names
FROM DEPARTMENTS D
JOIN EMPLOYEES E ON D.ID = E.DEPID
ORDER BY D.NAME
;




