CREATE VIEW Salary_Table AS 
SELECT DISTINCT D.NAME AS department_name,
TRUNC (AVG (DECODE (E.SEX, 'MALE', E.SALARY)) OVER (PARTITION BY D.ID), 2) AS avg_male_salary,
TRUNC (AVG (DECODE (E.SEX, 'FEMALE', E.SALARY)) OVER (PARTITION BY D.ID), 2) AS avg_female_salary
FROM DEPARTMENTS D
JOIN EMPLOYEES E ON D.ID = E.DEPID
ORDER BY D.NAME;

